import { useMemo } from "react";
import { AuditEntry } from "@/app/(DashboardLayout)/audit/types";

/**
 * Hook to get audit entry data by entry ID
 * The entry ID is a composite key generated from the entry data
 */
export function useAuditEntry(
  entryId: string | null,
  auditEntries: AuditEntry[]
): { data: AuditEntryData | null; isLoading: boolean } {
  const entry = useMemo(() => {
    if (!entryId) return null;

    // Find the entry that matches the ID exactly
    // The entryId is the full composite key generated by getEntryKey
    const foundEntry = auditEntries.find((entry, index) => {
      // Reconstruct the key the same way getEntryKey does
      if (entry.type === "onboarding") {
        const decision = entry.data;
        const id = decision.id ? String(decision.id) : null;
        const timestamp = decision.reviewedAt || decision.createdAt || null;
        const userId = decision.userId ? String(decision.userId) : (decision.user?.id ? String(decision.user.id) : decision.user?.uuid || null);
        const reviewedBy = decision.reviewedBy ? String(decision.reviewedBy) : null;
        const status = decision.status || 'unknown';
        const key = `onboarding-${id || 'no-id'}-${timestamp || 'no-time'}-${userId || 'no-user'}-${reviewedBy || 'no-reviewer'}-${status}-${index}`;
        return key === entryId;
      } else {
        const log = entry.data;
        const id = log.id ? String(log.id) : null;
        const subjectId = log.subjectId ? String(log.subjectId) : null;
        const timestamp = log.createdAt || null;
        const event = log.event || 'unknown';
        const causerId = log.causer?.id ? String(log.causer.id) : log.causer?.uuid || null;
        const key = `activity-log-${id || 'no-id'}-${subjectId || 'no-subject'}-${timestamp || 'no-time'}-${event}-${causerId || 'no-causer'}-${index}`;
        return key === entryId;
      }
    });

    if (!foundEntry) return null;

    // Transform entry to AuditEntryData format
    return transformEntryToData(foundEntry);
  }, [entryId, auditEntries]);

  return {
    data: entry,
    isLoading: false, // Data is already loaded, just finding it
  };
}

/**
 * Transform AuditEntry to AuditEntryData format for the dialog
 */
function transformEntryToData(entry: AuditEntry): AuditEntryData {
  if (entry.type === "onboarding") {
    const decision = entry.data;
    const timestamp = decision.reviewedAt
      ? new Date(decision.reviewedAt)
      : decision.createdAt
      ? new Date(decision.createdAt)
      : new Date();

    return {
      user: {
        name: decision.user?.name || "Unknown",
        email: decision.user?.email || "",
        avatarUrl: decision.user?.profile?.avatarUrl || null,
        department: extractDepartment(decision.user),
      },
      type: "Onboarding",
      action: decision.status === "approved" ? "Approved" : decision.status === "rejected" ? "Rejected" : "Pending",
      role: decision.assignedUserType || null,
      performedBy: decision.reviewedBy ? "Super Admin" : "System", // Onboarding is always by super admin
      date: timestamp,
      details: decision.rejectionReason || `User onboarding ${decision.status || "pending"}`,
    };
  } else {
    const log = entry.data;
    const timestamp = log.createdAt ? new Date(log.createdAt) : new Date();
    const user = log.subject || (log.subjectId ? { id: log.subjectId } : null);

    // Extract role from properties
    const role =
      log.properties?.attributes?.roles?.[0] ||
      log.properties?.old?.roles?.[0] ||
      null;

    // Get action label
    const actionLabels: Record<string, string> = {
      deactivated: "Deactivated",
      activated: "Activated",
      role_changed: "Role Changed",
      profile_updated: "Profile Updated",
      approved: "Approved",
      rejected: "Rejected",
      pending: "Pending",
    };
    const action = actionLabels[log.event] || log.event;

    // Get type
    const type = log.logName === "onboarding" ? "Onboarding" : "User Management";

    // Get performed by
    const performedBy = log.causer?.name || "System";

    // Get details
    const details = formatLogDetails(log);

    return {
      user: {
        name: (user as any)?.name || "Unknown",
        email: (user as any)?.email || "",
        avatarUrl: (user as any)?.profile?.avatarUrl || (user as any)?.avatarUrl || null,
        department: extractDepartment(user as any),
      },
      type,
      action,
      role,
      performedBy,
      date: timestamp,
      details,
    };
  }
}

/**
 * Extract department from user object
 */
function extractDepartment(user: any): string {
  if (!user) return "";
  
  const roles = user.profile?.roles || user.roles || [];
  const validDepartments = ["Owner Sales", "Renovation", "Technician", "Finance & Account"];
  
  const department = roles.find((role: string) => validDepartments.includes(role));
  return department || "";
}

/**
 * Format log details from activity log properties
 */
function formatLogDetails(log: any): string {
  if (!log.properties) {
    return log.description || "No details available";
  }

  const changes: string[] = [];
  const oldValues = log.properties.old || {};
  const newValues = log.properties.attributes || {};

  // Format common field changes
  const fieldMappings: Record<string, string> = {
    status: "Status",
    name: "Name",
    email: "Email",
    phone_no: "Phone Number",
    phoneNo: "Phone Number",
    country_code: "Country Code",
    countryCode: "Country Code",
    roles: "Role",
    department: "Department",
  };

  // Check for role changes
  if (oldValues.roles?.[0] !== newValues.roles?.[0]) {
    const oldRole = oldValues.roles?.[0] || "—";
    const newRole = newValues.roles?.[0] || "—";
    changes.push(`Role: ${oldRole} → ${newRole}`);
  }

  // Check for department changes
  if (oldValues.department !== newValues.department) {
    const oldDept = oldValues.department || "—";
    const newDept = newValues.department || "—";
    changes.push(`Department: ${oldDept} → ${newDept}`);
  }

  // Check for status changes
  if (oldValues.status !== newValues.status) {
    const oldStatus = oldValues.status || "—";
    const newStatus = newValues.status || "—";
    changes.push(`Status: ${oldStatus} → ${newStatus}`);
  }

  // Check for other field changes
  Object.keys(newValues).forEach((key) => {
    if (key === "roles" || key === "department" || key === "status") return; // Already handled
    if (oldValues[key] !== newValues[key]) {
      const fieldName = fieldMappings[key] || key;
      const oldVal = oldValues[key] || "—";
      const newVal = newValues[key] || "—";
      changes.push(`${fieldName}: ${oldVal} → ${newVal}`);
    }
  });

  if (changes.length > 0) {
    return changes.join(", ");
  }

  return log.description || "No changes recorded";
}

/**
 * Audit entry data format for the detail dialog
 */
export interface AuditEntryData {
  user: {
    name: string;
    email: string;
    avatarUrl: string | null;
    department: string;
  };
  type: string;
  action: string;
  role: string | null;
  performedBy: string;
  date: Date;
  details: string;
}

