import { useMemo } from "react";
import { AuditEntry } from "@/app/(DashboardLayout)/audit/types";

/**
 * Hook to get audit entry data by entry ID
 * The entry ID is a composite key generated from the entry data
 */
export function useAuditEntry(
  entryId: string | null,
  auditEntries: AuditEntry[]
): { data: AuditEntryData | null; isLoading: boolean } {
  const entry = useMemo(() => {
    if (!entryId) return null;

    // Find the entry that matches the ID exactly
    // The entryId is the full composite key generated by getEntryKey
    const foundEntry = auditEntries.find((entry, index) => {
      // Reconstruct the key the same way getEntryKey does
      if (entry.type === "onboarding") {
        const decision = entry.data;
        const id = decision.id ? String(decision.id) : null;
        const timestamp = decision.reviewedAt || decision.createdAt || null;
        const userId = decision.userId ? String(decision.userId) : (decision.user?.id ? String(decision.user.id) : decision.user?.uuid || null);
        const reviewedBy = decision.reviewedBy ? String(decision.reviewedBy) : null;
        const status = decision.status || 'unknown';
        const key = `onboarding-${id || 'no-id'}-${timestamp || 'no-time'}-${userId || 'no-user'}-${reviewedBy || 'no-reviewer'}-${status}-${index}`;
        return key === entryId;
      } else {
        const log = entry.data;
        const id = log.id ? String(log.id) : null;
        const subjectId = log.subjectId ? String(log.subjectId) : null;
        const timestamp = log.createdAt || null;
        const event = log.event || 'unknown';
        const causerId = log.causer?.id ? String(log.causer.id) : log.causer?.uuid || null;
        const key = `activity-log-${id || 'no-id'}-${subjectId || 'no-subject'}-${timestamp || 'no-time'}-${event}-${causerId || 'no-causer'}-${index}`;
        return key === entryId;
      }
    });

    if (!foundEntry) return null;

    // Transform entry to AuditEntryData format
    return transformEntryToData(foundEntry);
  }, [entryId, auditEntries]);

  return {
    data: entry,
    isLoading: false, // Data is already loaded, just finding it
  };
}

/**
 * Transform AuditEntry to AuditEntryData format for the dialog
 */
function transformEntryToData(entry: AuditEntry): AuditEntryData {
  if (entry.type === "onboarding") {
    const decision = entry.data;
    const timestamp = decision.reviewedAt
      ? new Date(decision.reviewedAt)
      : decision.createdAt
      ? new Date(decision.createdAt)
      : new Date();

    return {
      user: {
        name: decision.user?.name || "Unknown",
        email: decision.user?.email || "",
        avatarUrl: decision.user?.profile?.avatarUrl || null,
        department: extractDepartment(decision.user),
      },
      type: "Onboarding",
      action: decision.status === "approved" ? "Approved" : decision.status === "rejected" ? "Rejected" : "Pending",
      role: decision.assignedUserType || null,
      performedBy: decision.reviewedBy ? "Super Admin" : "System", // Onboarding is always by super admin
      date: timestamp,
      details: decision.rejectionReason || `User onboarding ${decision.status || "pending"}`,
    };
  } else {
    const log = entry.data;
    const timestamp = log.createdAt ? new Date(log.createdAt) : new Date();
    const user = log.subject || (log.subjectId ? { id: log.subjectId } : null);

    // Extract role from properties
    const role =
      log.properties?.attributes?.roles?.[0] ||
      log.properties?.old?.roles?.[0] ||
      null;

    // Get action label
    const actionLabels: Record<string, string> = {
      deactivated: "Deactivated",
      activated: "Activated",
      role_changed: "Role Changed",
      profile_updated: "Profile Updated",
      approved: "Approved",
      rejected: "Rejected",
      pending: "Pending",
    };
    const action = actionLabels[log.event] || log.event;

    // Get type
    const type = log.logName === "onboarding" ? "Onboarding" : "User Management";

    // Get performed by
    const performedBy = log.causer?.name || "System";

    // Get details
    const details = formatLogDetails(log);

    return {
      user: {
        name: (user as any)?.name || "Unknown",
        email: (user as any)?.email || "",
        avatarUrl: (user as any)?.profile?.avatarUrl || (user as any)?.avatarUrl || null,
        department: extractDepartment(user as any),
      },
      type,
      action,
      role,
      performedBy,
      date: timestamp,
      details,
    };
  }
}

/**
 * Extract department from user object
 */
function extractDepartment(user: any): string {
  if (!user) return "";
  
  const roles = user.profile?.roles || user.roles || [];
  const validDepartments = ["Owner Sales", "Renovation", "Technician", "Finance & Account"];
  
  const department = roles.find((role: string) => validDepartments.includes(role));
  return department || "";
}

/**
 * Format log details from activity log properties
 * Returns "-" for pending entries with no details
 */
function formatLogDetails(log: any): string {
  // Safety check: if log is null/undefined
  if (!log) {
    return "—";
  }

  // For pending entries, always return empty
  if (log.event === 'pending') {
    return "—";
  }

  if (!log.properties) {
    return "—";
  }

  const oldValues = log.properties.old || {};
  const newValues = log.properties.attributes || {};

  // If both old and attributes are empty, return empty
  if (Object.keys(oldValues).length === 0 && Object.keys(newValues).length === 0) {
    return "—";
  }

  const changes: string[] = [];

  // 1. Format status change (if status changed)
  if (oldValues.status && newValues.status && oldValues.status !== newValues.status) {
    changes.push(`Status: ${oldValues.status} → ${newValues.status}`);
  }

  // 2. Format role (for onboarding approvals or role changes)
  // Handle roles array (backend may send roles as array)
  const oldRole = Array.isArray(oldValues.roles) ? oldValues.roles[0] : oldValues.role || oldValues.roles?.[0];
  const newRole = Array.isArray(newValues.roles) ? newValues.roles[0] : newValues.role || newValues.roles?.[0];

  if (newRole) {
    if (oldRole && oldRole !== newRole) {
      // Role changed
      changes.push(`Role: ${oldRole} → ${newRole}`);
    } else if (!oldRole) {
      // Role assigned (no old role)
      changes.push(`Role: ${newRole}`);
    }
  }

  // 3. Format department (for onboarding approvals or department changes)
  if (newValues.department) {
    if (oldValues.department !== undefined && oldValues.department !== newValues.department) {
      // Department changed
      const oldDept = oldValues.department || 'null';
      changes.push(`Department: ${oldDept} → ${newValues.department}`);
    } else if (!oldValues.department) {
      // Department assigned (no old department)
      changes.push(`Department: ${newValues.department}`);
    }
  }

  // 4. Format other field changes (name, phone, etc. for user updates)
  Object.keys(newValues).forEach((key) => {
    // Skip these fields (already handled or metadata)
    if (['status', 'role', 'roles', 'department', 'module', 'ip', 'staff_onboarding_id'].includes(key)) {
      return;
    }

    const oldVal = oldValues[key];
    const newVal = newValues[key];

    // Only show if value actually changed
    if (oldVal !== undefined && newVal !== undefined && oldVal !== newVal) {
      // Format field name (convert snake_case to Title Case)
      const fieldName = key
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');

      // Format values
      const formatValue = (val: any): string => {
        if (val === null || val === undefined) return 'null';
        if (typeof val === 'boolean') return val ? 'Yes' : 'No';
        if (typeof val === 'object') return JSON.stringify(val);
        return String(val);
      };

      const oldFormatted = formatValue(oldVal);
      const newFormatted = formatValue(newVal);

      changes.push(`${fieldName}: "${oldFormatted}" → "${newFormatted}"`);
    }
  });

  // Also check for fields that were removed (in old but not in new)
  Object.keys(oldValues).forEach((key) => {
    // Skip already handled fields
    if (['status', 'role', 'roles', 'department', 'module', 'ip', 'staff_onboarding_id'].includes(key)) {
      return;
    }

    // Only show if field was removed (exists in old but not in new)
    if (oldValues[key] !== undefined && newValues[key] === undefined) {
      const fieldName = key
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');

      const formatValue = (val: any): string => {
        if (val === null || val === undefined) return 'null';
        if (typeof val === 'boolean') return val ? 'Yes' : 'No';
        if (typeof val === 'object') return JSON.stringify(val);
        return String(val);
      };

      const oldFormatted = formatValue(oldValues[key]);
      changes.push(`${fieldName}: "${oldFormatted}" → null`);
    }
  });

  return changes.length > 0 ? changes.join(", ") : "—";
}

/**
 * Audit entry data format for the detail dialog
 */
export interface AuditEntryData {
  user: {
    name: string;
    email: string;
    avatarUrl: string | null;
    department: string;
  };
  type: string;
  action: string;
  role: string | null;
  performedBy: string;
  date: Date;
  details: string;
}

